---
# tasks file for ansible

# roles/example/tasks/debian.yml
- name: Install web server
  ansible.builtin.apt:
    name: "{{item}}"
    state: present
  loop: "{{ pkgs }}"
  become: yes

# Create the Services Directory
- name: Create the Services Directory
  file:
    path:  "/srv"
    owner: "2001"
    group: "2001"
    mode:
    state: directory

- name: Clone the NameD Service
  git:
    repo: https://github.com/galaxy3-net/named.git
    dest: /srv/named
    version: master
  become: yes


#- name: Start NameD Service
#  name: named
#  state: started