---
# tasks file for ansible

# roles/example/tasks/debian.yml
- name: Install Packages
  ansible.builtin.apt:
    name: "{{item}}"
    state: present
  loop: "{{ pkgs }}"
  become: yes

#
- name: Create theDr
  user:
    name: thedr
    uid: 2001
    shell: /bin/bash
    comment: "Master of the Universe"
    home: /thedr
  become: yes

# Create the Services Directory
- name: Create the Services Directory
  file:
    path:  "/srv"
    owner: thedr
    group: thedr
    mode:
    state: directory
  become: yes

- name: Clone the NameD Service
  git:
    repo: "https://github.com/galaxy3-net/named.git"
    dest: /srv/
    # separate_git_dir: /tmp/named.git
    version: master
  become: yes

- name: Fix Repo Ownership
  file:
    path: /srv
    owner: thedr
    group: thedr
    state: directory
    recurse: yes

#- name: Start NameD Service
#  name: named
#  state: started