---
# tasks file for ansible

# roles/example/tasks/debian.yml
- name: Install Packages
  ansible.builtin.apt:
    name: "{{item}}"
    state: present
  loop: "{{ pkgs }}"
  become: yes

#
- name: Create theDr
  user:
    name: thedr
    uid: 2001
    shell: /bin/bash
    comment: "Master of the Universe"
    home: /thedr
  become: yes

# Create the Services Directory
- name: Create the Services Directory
  file:
    path:  "/srv"
    owner: thedr
    group: thedr
    mode:
    state: directory
  become: yes

- name: Clone the NameD Service
  git:
    repo: "https://github.com/galaxy3-net/named.git"
    dest: /srv/named
    separate_git_dir: /srv/named.git
    version: master
  become: yes

- name: Fix Repo Ownership
  file:
    path: /srv
    owner: thedr
    group: thedr
    state: directory
    recurse: yes
  become: yes

- name: Create sbin file
  command:
    cmd:     cp /srv/named/usr/sbin/named /usr/sbin/named && chmod u+x
    creates: /usr/sbin/named
  become: yes

- name: Copy Service Config File
  command:
    cmd: cp /srv/named/etc/supervisor/conf.d/named.conf /etc/supervisor/conf.d/.
    creates: /etc/supervisor/conf.d/named.conf
  become: yes

- name: Start NameD Service
  supervisorctl:
    name: named
    #config: /srv/named/etc/supervisor/conf.d/named.conf
    state: started
  become: yes