---
# tasks file for ansible

# roles/example/tasks/debian.yml
#- name: Install Packages
#  ansible.builtin.apt:
#    name: "{{item}}"
#    state: present
#  loop: "{{ pkgs }}"
#  become: yes

#
- name: Create theDr
  user:
    name: thedr
    uid: 2001
    shell: /bin/bash
    comment: "Master of the Universe"
    home: /thedr
  become: yes

# Create the Services Directory
- name: Create the Services Directory
  file:
    path:  "/srv"
    owner: thedr
    group: thedr
    mode:
    state: directory
  become: yes


- name: Remove resolv.conf
  file:
    path: /etc/resolv.conf
    state: absent
  become: yes

- name: Update Resolver /etc/resolv.conf
  lineinfile:
    path: /etc/resolv.conf
    line: '{{ item.line }}'
    state: '{{ item.state }}'
    create: yes
    backup: true
  loop:
    - { state: 'absent', line: 'options edns0' }
    - { state: 'absent', line: 'search attlocal.net' }
    - { state: "present", line: "nameserver 10.55.55.2" }
    - { state: "present",  line: "nameserver 8.8.8.8" }
    - { state: "present",  line: "options edns0" }
    - { state: "present",  line: "nameserver 8.8.8.8" }
    - { state: "present",  line: 'search moddell.galaxy3.net attlocal.net, empire.local' }
  become: yes